// Extended mock data for comprehensive demo experience
// This provides realistic sample professionals and organizations

export const extendedMockProfessionals = [
  {
    id: 1,
    userId: "prof-1",
    name: "Dr. Sarah Johnson",
    specialties: ["Emergency Medicine", "Trauma Surgery"],
    languages: ["English", "French", "Arabic"],
    certifications: ["ATLS", "ACLS", "PALS", "Diploma in Tropical Medicine"],
    experience: 8,
    availabilityStatus: "Available",
    availableFrom: "2024-02-01",
    preferredDuration: "3-6 months",
    licenseVerified: true,
    bio: "Experienced emergency physician with 8+ years in humanitarian medicine. Specialized in trauma care and epidemic response.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "United States",
    email: "sarah.johnson@email.com"
  },
  {
    id: 2,
    userId: "prof-2",
    name: "Dr. Michael Chen",
    specialties: ["Surgery", "Orthopedics"],
    languages: ["English", "Mandarin", "Spanish"],
    certifications: ["ATLS", "AO Trauma", "SICOT"],
    experience: 12,
    availabilityStatus: "Available",
    availableFrom: "2024-03-01",
    preferredDuration: "6-12 months",
    licenseVerified: true,
    bio: "Orthopedic surgeon with extensive experience in disaster response and conflict zones. Specialized in complex trauma reconstruction.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "Canada",
    email: "michael.chen@email.com"
  },
  {
    id: 3,
    userId: "prof-3",
    name: "Dr. Fatima Al-Rashid",
    specialties: ["Pediatrics", "Infectious Diseases"],
    languages: ["Arabic", "English", "French"],
    certifications: ["PALS", "Tropical Medicine Diploma", "WHO Emergency Response"],
    experience: 6,
    availabilityStatus: "Available",
    availableFrom: "2024-02-15",
    preferredDuration: "3-6 months",
    licenseVerified: true,
    bio: "Pediatric infectious disease specialist with focus on epidemic response and malnutrition treatment in crisis settings.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "Jordan",
    email: "fatima.alrashid@email.com"
  },
  {
    id: 4,
    userId: "prof-4",
    name: "Dr. James Mitchell",
    specialties: ["Anesthesiology", "Critical Care"],
    languages: ["English", "Portuguese"],
    certifications: ["Board Certified Anesthesiology", "Critical Care Medicine", "ACLS"],
    experience: 10,
    availabilityStatus: "On Deployment",
    availableFrom: "2024-04-01",
    preferredDuration: "6-9 months",
    licenseVerified: true,
    bio: "Critical care anesthesiologist with experience in resource-limited settings. Currently completing deployment in Haiti.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "United Kingdom",
    email: "james.mitchell@email.com"
  },
  {
    id: 5,
    userId: "prof-5",
    name: "Dr. Maria Rodriguez",
    specialties: ["Obstetrics & Gynecology", "Maternal Health"],
    languages: ["Spanish", "English", "Portuguese"],
    certifications: ["OBGYN Board Certified", "EmONC", "ALSO"],
    experience: 9,
    availabilityStatus: "Available",
    availableFrom: "2024-02-20",
    preferredDuration: "4-8 months",
    licenseVerified: true,
    bio: "Maternal health specialist focused on reducing maternal mortality in humanitarian crises. Expert in emergency obstetric care.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "Spain",
    email: "maria.rodriguez@email.com"
  },
  {
    id: 6,
    userId: "prof-6",
    name: "Dr. David Kim",
    specialties: ["Mental Health", "Psychiatry"],
    languages: ["English", "Korean", "Japanese"],
    certifications: ["Board Certified Psychiatry", "PTSD Specialist", "Crisis Counseling"],
    experience: 7,
    availabilityStatus: "Available",
    availableFrom: "2024-03-10",
    preferredDuration: "3-6 months",
    licenseVerified: true,
    bio: "Psychiatrist specializing in trauma and PTSD treatment for conflict-affected populations and humanitarian workers.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "South Korea",
    email: "david.kim@email.com"
  },
  {
    id: 7,
    userId: "prof-7",
    name: "Dr. Amara Okafor",
    specialties: ["Public Health", "Epidemiology"],
    languages: ["English", "French", "Igbo"],
    certifications: ["MPH", "Field Epidemiology", "WHO GOARN"],
    experience: 5,
    availabilityStatus: "Available",
    availableFrom: "2024-02-05",
    preferredDuration: "2-4 months",
    licenseVerified: true,
    bio: "Public health specialist with expertise in outbreak investigation and epidemic response in West and Central Africa.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "Nigeria",
    email: "amara.okafor@email.com"
  },
  {
    id: 8,
    userId: "prof-8",
    name: "Dr. Emma Thompson",
    specialties: ["Family Medicine", "Primary Care"],
    languages: ["English", "Swahili"],
    certifications: ["Family Medicine Board", "Tropical Medicine", "Primary Care"],
    experience: 4,
    availabilityStatus: "Available",
    availableFrom: "2024-02-25",
    preferredDuration: "6-12 months",
    licenseVerified: true,
    bio: "Family physician with experience in rural and refugee health programs. Skilled in community health education and program development.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "Australia",
    email: "emma.thompson@email.com"
  },
  {
    id: 9,
    userId: "prof-9",
    name: "Dr. Ahmed Hassan",
    specialties: ["Cardiology", "Internal Medicine"],
    languages: ["Arabic", "English", "German"],
    certifications: ["Cardiology Board", "ACLS", "European Cardiology"],
    experience: 11,
    availabilityStatus: "Available",
    availableFrom: "2024-03-15",
    preferredDuration: "4-6 months",
    licenseVerified: true,
    bio: "Interventional cardiologist with experience in emergency cardiac care in resource-limited settings. Previous deployments in Syria and Yemen.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "Germany",
    email: "ahmed.hassan@email.com"
  },
  {
    id: 10,
    userId: "prof-10",
    name: "Dr. Lisa Anderson",
    specialties: ["Nursing", "Critical Care Nursing"],
    languages: ["English", "Norwegian"],
    certifications: ["RN", "CCRN", "Emergency Nursing", "WHO Field Training"],
    experience: 7,
    availabilityStatus: "Available",
    availableFrom: "2024-02-10",
    preferredDuration: "3-9 months",
    licenseVerified: true,
    bio: "Critical care nurse with extensive experience in emergency response and patient stabilization in humanitarian crises.",
    profileImageUrl: "/api/placeholder/80/80",
    location: "Norway",
    email: "lisa.anderson@email.com"
  }
];

export const extendedMockOrganizations = [
  {
    id: 1,
    name: "Médecins Sans Frontières",
    type: "International NGO",
    country: "International",
    description: "International medical humanitarian organization providing emergency aid to people affected by conflict, epidemics, disasters, or exclusion from healthcare.",
    website: "msf.org",
    contactEmail: "recruitment@msf.org",
    verified: true,
    activeDeployments: 45,
    specialtiesNeeded: ["Emergency Medicine", "Surgery", "Pediatrics", "Mental Health"],
    profileImageUrl: "/api/placeholder/80/80"
  },
  {
    id: 2,
    name: "International Red Cross",
    type: "International Organization",
    country: "Switzerland",
    description: "Humanitarian organization providing emergency assistance, disaster relief, and disaster preparedness education worldwide.",
    website: "icrc.org",
    contactEmail: "careers@icrc.org",
    verified: true,
    activeDeployments: 32,
    specialtiesNeeded: ["Surgery", "Emergency Medicine", "Public Health", "Nursing"],
    profileImageUrl: "/api/placeholder/80/80"
  },
  {
    id: 3,
    name: "Save the Children",
    type: "International NGO",
    country: "United Kingdom",
    description: "International non-governmental organization that promotes children's rights, provides relief and helps support children in developing countries.",
    website: "savethechildren.org",
    contactEmail: "global.recruitment@savethechildren.org",
    verified: true,
    activeDeployments: 28,
    specialtiesNeeded: ["Pediatrics", "Nutrition", "Mental Health", "Public Health"],
    profileImageUrl: "/api/placeholder/80/80"
  },
  {
    id: 4,
    name: "World Health Organization",
    type: "UN Agency",
    country: "Switzerland",
    description: "Specialized agency of the United Nations responsible for international public health, leading global health responses and emergency preparedness.",
    website: "who.int",
    contactEmail: "hrd@who.int",
    verified: true,
    activeDeployments: 41,
    specialtiesNeeded: ["Public Health", "Epidemiology", "Emergency Medicine", "Infectious Diseases"],
    profileImageUrl: "/api/placeholder/80/80"
  },
  {
    id: 5,
    name: "UNICEF",
    type: "UN Agency",
    country: "United States",
    description: "United Nations Children's Fund providing humanitarian and developmental aid to children worldwide, focusing on health, education, and protection.",
    website: "unicef.org",
    contactEmail: "jobs@unicef.org",
    verified: true,
    activeDeployments: 35,
    specialtiesNeeded: ["Pediatrics", "Nutrition", "Mental Health", "Public Health"],
    profileImageUrl: "/api/placeholder/80/80"
  },
  {
    id: 6,
    name: "Partners In Health",
    type: "NGO",
    country: "United States",
    description: "Non-profit healthcare organization working in poor communities to strengthen health systems and provide high-quality healthcare.",
    website: "pih.org",
    contactEmail: "careers@pih.org",
    verified: true,
    activeDeployments: 22,
    specialtiesNeeded: ["Internal Medicine", "Infectious Diseases", "Surgery", "Mental Health"],
    profileImageUrl: "/api/placeholder/80/80"
  },
  {
    id: 7,
    name: "Emergency Medical Corps",
    type: "Medical NGO",
    country: "Canada",
    description: "Rapid response medical organization specializing in emergency healthcare delivery in crisis situations and disaster zones.",
    website: "emergencymedcorps.org",
    contactEmail: "deployment@emergencymedcorps.org",
    verified: true,
    activeDeployments: 18,
    specialtiesNeeded: ["Emergency Medicine", "Trauma Surgery", "Critical Care", "Anesthesiology"],
    profileImageUrl: "/api/placeholder/80/80"
  },
  {
    id: 8,
    name: "Humanitarian Health Alliance",
    type: "Coalition",
    country: "International",
    description: "Global alliance of healthcare organizations coordinating medical responses to humanitarian crises and building local capacity.",
    website: "humanitarianhealthalliance.org",
    contactEmail: "partnerships@hha.org",
    verified: true,
    activeDeployments: 25,
    specialtiesNeeded: ["Public Health", "Training & Capacity Building", "Emergency Medicine", "Surgery"],
    profileImageUrl: "/api/placeholder/80/80"
  }
];